# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af4219b8c99f106ed0c301e0845ae3833ec32ee680911759023c2eed38a60becf245336d3ec6f899a3aefcbba554c03ff270405240bf592bcd612552f311337d

test:
  secret_key_base: bb7c6a883d98a12f67e835d7cda83fbe09981a4a7d9608cf1f3b37bea01c48529ba7715dd2ec29cdc242d2c42edb86df59bb5b02862b709ed554299a2c96d3ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
